<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Guideline [
	<!-- gxml-v1.dtd version 0.7 -->
	<!ELEMENT Guideline (EDSFileName?, InternalFormat, DocumentProperties?, DocumentOptions?, Transaction, StandardCodes?)>
	<!ATTLIST Guideline
	Version CDATA #FIXED "96a"
>
	<!ELEMENT EDSFileName (#PCDATA)>
	<!ELEMENT InternalFormat (#PCDATA)>
	<!-- Document Properties -->
	<!ELEMENT DocumentProperties (Title?, Subject?, AuthorName?, TradingPartner?, Keywords?, Version?, VersionNbr?, CreationDate?, LastModified?, PublishDate?, GuidelineNotes?, IndustryType?)>
	<!ELEMENT Title (#PCDATA)>
	<!ELEMENT Subject (#PCDATA)>
	<!ELEMENT AuthorName (#PCDATA)>
	<!ELEMENT TradingPartner (#PCDATA)>
	<!ELEMENT Keywords (#PCDATA)>
	<!ELEMENT Version (#PCDATA)>
	<!ELEMENT VersionNbr (#PCDATA)>
	<!ELEMENT CreationDate (#PCDATA)>
	<!ELEMENT LastModified (#PCDATA)>
	<!ELEMENT PublishDate (#PCDATA)>
	<!ELEMENT GuidelineNotes (#PCDATA)>
	<!ELEMENT IndustryType (#PCDATA)>
	<!-- Document Options -->
	<!ELEMENT DocumentOptions (Labels*, Usages?, Lists?)>
	<!ELEMENT Labels (Label*)>
	<!ATTLIST Labels
	ApplyTo CDATA #REQUIRED
>
	<!ELEMENT Label (#PCDATA)>
	<!ATTLIST Label
	LabelID CDATA #REQUIRED
>
	<!ELEMENT Usages (Usage*)>
	<!ELEMENT Usage (#PCDATA)>
	<!ATTLIST Usage
	UsageID CDATA #REQUIRED
>
	<!ELEMENT Lists (List*)>
	<!ELEMENT List (ListValue*)>
	<!ATTLIST List
	ListID CDATA #REQUIRED
>
	<!ELEMENT ListValue (#PCDATA)>
	<!ATTLIST ListValue
	Index CDATA #REQUIRED
>
	<!-- Transaction -->
	<!ELEMENT Transaction (ID, Name, Purpose?, MessageStatus?, GroupID?, Standard?, StdVersion?, Notes?, MiscInfo?, ChildNodes?)>
	<!-- Loop -->
	<!ELEMENT Loop (ID, Name?, StdRequirement, UsrRequirement?, Area, Sequence, Count, Excluded?, Notes?, MiscInfo?, ChildNodes*)>
	<!-- Segment -->
	<!ELEMENT Segment (ID, Name, StdRequirement, UsrRequirement?, Area, Sequence, MaxUse, Excluded?, Notes?, MiscInfo?, ChildNodes*)>
	<!-- Composite -->
	<!ELEMENT Composite (ID, Name, StdRequirement, UsrRequirement?, Sequence, MaxUse?, Excluded?, Notes?, ApplicationFields?, MiscInfo?, ChildNodes*)>
	<!-- Element  -->
	<!ELEMENT Element (ID, Name, StdRequirement, UsrRequirement?, Sequence, DataType, MinSize, MaxSize, MaxUse?, Excluded?, Notes?, ApplicationFields?, MiscInfo?, ChildNodes*)>
	<!-- ApplicationFields  -->
	<!ELEMENT ApplicationFields (FieldName?, RecordName?, Example?, Mode?, Control?, FieldLabel?, Format?, Notes?)>
	<!ELEMENT FieldName (#PCDATA)>
	<!ELEMENT RecordName (#PCDATA)>
	<!ELEMENT Example (#PCDATA)>
	<!ELEMENT Mode (#PCDATA)>
	<!ELEMENT FieldLabel (#PCDATA)>
	<!ELEMENT Control (#PCDATA)>
	<!ELEMENT Format (#PCDATA)>
	<!-- Standard Codes For Element -->
	<!ELEMENT StdCodes (Code*)>
	<!ATTLIST StdCodes
	IDREF IDREF #REQUIRED
		IncludeStd CDATA #REQUIRED
>
	<!-- User Defined Codes For Element -->
	<!ELEMENT UserDefinedCodes (Code*)>
	<!-- Standard Code List For Guideline -->
	<!ELEMENT StandardCodes (ElementCode*)>
	<!-- Code List For Element -->
	<!ELEMENT ElementCode (Code*)>
	<!ATTLIST ElementCode
	ID ID #REQUIRED
>
	<!-- Code -->
	<!ELEMENT Code (CodeValue?, CodeName?, Notes?, MiscInfo?)>
	<!ATTLIST Code
	ID ID #IMPLIED
		IDREF IDREF #IMPLIED
>
	<!-- Common Nodes -->
	<!ELEMENT Area (#PCDATA)>
	<!ELEMENT ChildNodes ANY>
	<!ELEMENT CodeValue (#PCDATA)>
	<!ELEMENT CodeName (#PCDATA)>
	<!ELEMENT Count (#PCDATA)>
	<!ELEMENT DataType (#PCDATA)>
	<!ELEMENT Excluded (#PCDATA)>
	<!ELEMENT Excuded (#PCDATA)>
	<!ELEMENT GroupID (#PCDATA)>
	<!ELEMENT ID (#PCDATA)>
	<!ELEMENT MaxSize (#PCDATA)>
	<!ELEMENT MaxUse (#PCDATA)>
	<!ELEMENT MessageStatus (#PCDATA)>
	<!ELEMENT MinSize (#PCDATA)>
	<!ELEMENT MiscInfo ANY>
	<!ELEMENT Name (#PCDATA)>
	<!ELEMENT Notes (Note*)>
	<!ELEMENT Note (#PCDATA)>
	<!ATTLIST Note
	Type CDATA #REQUIRED
>
	<!ELEMENT Purpose (#PCDATA)>
	<!ELEMENT Sequence (#PCDATA)>
	<!ELEMENT Standard (#PCDATA)>
	<!ELEMENT StdRequirement (#PCDATA)>
	<!ELEMENT StdVersion (#PCDATA)>
	<!ELEMENT UsrRequirement (#PCDATA)>
]>
<Guideline Version="96a">
	<InternalFormat>EDI</InternalFormat>
	<DocumentProperties>
		<Title/>
		<Subject/>
		<AuthorName/>
		<TradingPartner/>
		<Keywords/>
		<Version>0</Version>
		<VersionNbr>1.0</VersionNbr>
		<CreationDate>15/11/2004</CreationDate>
		<LastModified/>
		<PublishDate/>
		<GuidelineNotes/>
		<IndustryType/>
	</DocumentProperties>
	<DocumentOptions>
		<Labels ApplyTo="Sets">
			<Label LabelID="UserNote1">User Note 1</Label>
			<Label LabelID="UserNote2">User Note 2</Label>
			<Label LabelID="UserNote3">User Note 3</Label>
			<Label LabelID="UserNote4">User Note 4</Label>
			<Label LabelID="UserNote5">User Note 5</Label>
		</Labels>
		<Labels ApplyTo="Segments">
			<Label LabelID="UserNote1">User Note 1</Label>
			<Label LabelID="UserNote2">User Note 2</Label>
			<Label LabelID="UserNote3">User Note 3</Label>
			<Label LabelID="UserNote4">User Note 4</Label>
			<Label LabelID="UserNote5">User Note 5</Label>
		</Labels>
		<Labels ApplyTo="Elements">
			<Label LabelID="UserNote1">User Note 1</Label>
			<Label LabelID="UserNote2">User Note 2</Label>
			<Label LabelID="UserNote3">User Note 3</Label>
			<Label LabelID="UserNote4">User Note 4</Label>
			<Label LabelID="UserNote5">User Note 5</Label>
			<Label LabelID="UserNote6">User Note 6</Label>
		</Labels>
		<Labels ApplyTo="Codes">
			<Label LabelID="UserNote1">User Note 1</Label>
			<Label LabelID="UserNote2">User Note 2</Label>
			<Label LabelID="UserNote3">User Note 3</Label>
			<Label LabelID="UserNote4">User Note 4</Label>
			<Label LabelID="UserNote5">User Note 5</Label>
		</Labels>
		<Labels ApplyTo="Application">
			<Label LabelID="Mode">Mode</Label>
			<Label LabelID="Control">Control</Label>
			<Label LabelID="Label">Label</Label>
			<Label LabelID="Format">Format</Label>
		</Labels>
		<Usages>
			<Usage UsageID="Used">Used</Usage>
			<Usage UsageID="Must_use">Must use</Usage>
			<Usage UsageID="Not_used">Not used</Usage>
			<Usage UsageID="Recommended">Recommended</Usage>
			<Usage UsageID="Not_Recommended">Not recommended</Usage>
			<Usage UsageID="Future_use">Future</Usage>
			<Usage UsageID="Dependent">Dependent</Usage>
		</Usages>
		<Lists>
			<List ListID="Mode">
				<ListValue Index="0">Automatic</ListValue>
				<ListValue Index="1">Calculated</ListValue>
				<ListValue Index="2">User Input</ListValue>
			</List>
			<List ListID="Control">
				<ListValue Index="0">Text</ListValue>
				<ListValue Index="1">Menu</ListValue>
				<ListValue Index="2">List</ListValue>
				<ListValue Index="3">Radio Button</ListValue>
				<ListValue Index="4">Check Box</ListValue>
			</List>
		</Lists>
	</DocumentOptions>
	<!--UN Sections same-->
	<Transaction>
		<ID>INVOIC</ID>
		<Name>INVOICE MESSAGE</Name>
		<Purpose>A message claiming payment for goods or services supplied under conditions agreed between the seller and the buyer.</Purpose>
		<MessageStatus>2</MessageStatus>
		<Standard>EDIFACT</Standard>
		<StdVersion>D96A</StdVersion>
		<ChildNodes>
			<Segment>
				<ID>UNB</ID>
				<Name>INTERCHANGE HEADER</Name>
				<StdRequirement>M</StdRequirement>
				<UsrRequirement>U</UsrRequirement>
				<Area>0</Area>
				<Sequence/>
				<MaxUse>1</MaxUse>
				<Notes>
					<Note Type="Purpose">To start, identify and specify an interchange.</Note>
				</Notes>
				<ChildNodes>
					<Composite>
						<ID>S001</ID>
						<Name>SYNTAX IDENTIFIER</Name>
						<StdRequirement>M</StdRequirement>
						<UsrRequirement>MU</UsrRequirement>
						<Sequence>010</Sequence>
						<MaxUse>1</MaxUse>
						<Notes>
							<Note Type="Description">Identification of the agency controlling the syntax and  indication of syntax level.</Note>
						</Notes>
						<ChildNodes>
							<Element>
								<ID>0001</ID>
								<Name>Syntax identifier</Name>
								<StdRequirement>M</StdRequirement>
								<UsrRequirement>U</UsrRequirement>
								<Sequence>010</Sequence>
								<DataType>a</DataType>
								<MinSize>4</MinSize>
								<MaxSize>4</MaxSize>
								<MaxUse>1</MaxUse>
								<Notes>
									<Note Type="Description">Coded identification of the agency controlling a syntax and  syntax level used in an interchange.</Note>
								</Notes>
								<ChildNodes>
									<StdCodes IDREF="CD.0001" IncludeStd="Std"/>
								</ChildNodes>
							</Element>
							<Element>
								<ID>0002</ID>
								<Name>Syntax version number</Name>
								<StdRequirement>M</StdRequirement>
								<UsrRequirement>U</UsrRequirement>
								<Sequence>020</Sequence>
								<DataType>n</DataType>
								<MinSize>1</MinSize>
								<MaxSize>1</MaxSize>
								<MaxUse>1</MaxUse>
								<Notes>
									<Note Type="Description">Version number of the syntax identified in the syntax  identifier (0001).</Note>
								</Notes>
							</Element>
						</ChildNodes>
					</Composite>
					<Composite>
						<ID>S002</ID>
						<Name>INTERCHANGE SENDER</Name>
						<StdRequirement>M</StdRequirement>
						<UsrRequirement>MU</UsrRequirement>
						<Sequence>020</Sequence>
						<MaxUse>1</MaxUse>
						<Notes>
							<Note Type="Description">Identification of the sender of the interchange.</Note>
						</Notes>
						<ChildNodes>
							<Element>
								<ID>0004</ID>
								<Name>Sender identification</Name>
								<StdRequirement>M</StdRequirement>
								<UsrRequirement>U</UsrRequirement>
								<Sequence>010</Sequence>
								<DataType>an</DataType>
								<MinSize>1</MinSize>
								<MaxSize>35</MaxSize>
								<MaxUse>1</MaxUse>
								<Notes>
									<Note Type="Description">Name or coded representation of the sender of a data  interchange.</Note>
								</Notes>
							</Element>
							<Element>
								<ID>0007</ID>
								<Name>Partner identification code qualifier</Name>
								<StdRequirement>C</StdRequirement>
								<UsrRequirement>U</UsrRequirement>
								<Sequence>020</Sequence>
								<DataType>an</DataType>
								<MinSize>1</MinSize>
								<MaxSize>4</MaxSize>
								<MaxUse>1</MaxUse>
								<Notes>
									<Note Type="Description">Qualifier referring to the source of codes for the  identifiers of interchanging partners.</Note>
								</Notes>
								<ChildNodes>
									<StdCodes IDREF="CD.0007" IncludeStd="Std"/>
								</ChildNodes>
							</Element>
							<Element>
								<ID>0008</ID>
								<Name>Address for reverse routing</Name>
								<StdRequirement>C</StdRequirement>
								<UsrRequirement>U</UsrRequirement>
								<Sequence>030</Sequence>
								<DataType>an</DataType>
								<MinSize>1</MinSize>
								<MaxSize>14</MaxSize>
								<MaxUse>1</MaxUse>
								<Notes>
									<Note Type="Description">Address specified by the sender of an interchange to be  included by the recipient in the response interchanges to  facilitate internal routing.</Note>
								</Notes>
							</Element>
						</ChildNodes>
					</Composite>
					<Composite>
						<ID>S003</ID>
						<Name>INTERCHANGE RECIPIENT</Name>
						<StdRequirement>M</StdRequirement>
						<UsrRequirement>MU</UsrRequirement>
						<Sequence>030</Sequence>
						<MaxUse>1</MaxUse>
						<Notes>
							<Note Type="Description">Identification of the recipient of the interchange.</Note>
						</Notes>
						<ChildNodes>
							<Element>
								<ID>0010</ID>
								<Name>Recipient identification</Name>
								<StdRequirement>M</StdRequirement>
								<UsrRequirement>U</UsrRequirement>
								<Sequence>010</Sequence>
								<DataType>an</DataType>
								<MinSize>1</MinSize>
								<MaxSize>35</MaxSize>
								<MaxUse>1</MaxUse>
								<Notes>
									<Note Type="Description">Name or coded representation of the recipient of a data  interchange.</Note>
								</Notes>
							</Element>
							<Element>
								<ID>0007</ID>
								<Name>Partner identification code qualifier</Name>
								<StdRequirement>C</StdRequirement>
								<UsrRequirement>U</UsrRequirement>
								<Sequence>020</Sequence>
								<DataType>an</DataType>
								<MinSize>1</MinSize>
								<MaxSize>4</MaxSize>
								<MaxUse>1</MaxUse>
								<Notes>
									<Note Type="Description">Qualifier referring to the source of codes for the  identifiers of interchanging partners.</Note>
								</Notes>
								<ChildNodes>
									<StdCodes IDREF="CD.0007" IncludeStd="Std"/>
								</ChildNodes>
							</Element>
							<Element>
								<ID>0014</ID>
								<Name>Routing address</Name>
								<StdRequirement>C</StdRequirement>
								<UsrRequirement>U</UsrRequirement>
								<Sequence>030</Sequence>
								<DataType>an</DataType>
								<MinSize>1</MinSize>
								<MaxSize>14</MaxSize>
								<MaxUse>1</MaxUse>
								<Notes>
									<Note Type="Description">Address specified by the recipient of an interchange to be  included by the sender and used by the recipient for  routing of received interchanges inside his organization.</Note>
								</Notes>
							</Element>
						</ChildNodes>
					</Composite>
					<Composite>
						<ID>S004</ID>
						<Name>DATE/TIME OF PREPARATION</Name>
						<StdRequirement>M</StdRequirement>
						<UsrRequirement>MU</UsrRequirement>
						<Sequence>040</Sequence>
						<MaxUse>1</MaxUse>
						<Notes>
							<Note Type="Description">Date/time of preparation of the interchange.</Note>
						</Notes>
						<ChildNodes>
							<Element>
								<ID>0017</ID>
								<Name>Date of preparation</Name>
								<StdRequirement>M</StdRequirement>
								<UsrRequirement>U</UsrRequirement>
								<Sequence>010</Sequence>
								<DataType>n</DataType>
								<MinSize>6</MinSize>
								<MaxSize>6</MaxSize>
								<MaxUse>1</MaxUse>
								<Notes>
									<Note Type="Description">Local date when an interchange or a functional group was  prepared.</Note>
								</Notes>
							</Element>
							<Element>
								<ID>0019</ID>
								<Name>Time of preparation</Name>
								<StdRequirement>M</StdRequirement>
								<UsrRequirement>U</UsrRequirement>
								<Sequence>020</Sequence>
								<DataType>n</DataType>
								<MinSize>4</MinSize>
								<MaxSize>4</MaxSize>
								<MaxUse>1</MaxUse>
								<Notes>
									<Note Type="Description">Local time of day when an interchange or a functional group  was prepared.</Note>
								</Notes>
							</Element>
						</ChildNodes>
					</Composite>
					<Element>
						<ID>0020</ID>
						<Name>Interchange control reference</Name>
						<StdRequirement>M</StdRequirement>
						<UsrRequirement>MU</UsrRequirement>
						<Sequence>050</Sequence>
						<DataType>an</DataType>
						<MinSize>1</MinSize>
						<MaxSize>14</MaxSize>
						<MaxUse>1</MaxUse>
						<Notes>
							<Note Type="Description">Unique reference assigned by the sender to an interchange.</Note>
						</Notes>
					</Element>
					<Composite>
						<ID>S005</ID>
						<Name>RECIPIENTS REFERENCE PASSWORD</Name>
						<StdRequirement>C</StdRequirement>
						<UsrRequirement>U</UsrRequirement>
						<Sequence>060</Sequence>
						<MaxUse>1</MaxUse>
						<Notes>
							<Note Type="Description">Reference or password as agreed between the communicating  partners.</Note>
						</Notes>
						<ChildNodes>
							<Element>
								<ID>0022</ID>
								<Name>Recipient's reference/password</Name>
								<StdRequirement>M</StdRequirement>
								<UsrRequirement>U</UsrRequirement>
								<Sequence>010</Sequence>
								<DataType>an</DataType>
								<MinSize>1</MinSize>
								<MaxSize>14</MaxSize>
								<MaxUse>1</MaxUse>
								<Notes>
									<Note Type="Description">Unique reference assigned by the recipient to the data  interchange or a password to the recipient's system or to a  third party network as specified in the partners  interchange agreement.</Note>
								</Notes>
							</Element>
							<Element>
								<ID>0025</ID>
								<Name>Recipient's reference/password qualifier</Name>
								<StdRequirement>C</StdRequirement>
								<UsrRequirement>U</UsrRequirement>
								<Sequence>020</Sequence>
								<DataType>an</DataType>
								<MinSize>2</MinSize>
								<MaxSize>2</MaxSize>
								<MaxUse>1</MaxUse>
								<Notes>
									<Note Type="Description">Qualifier for the recipient's reference or password.</Note>
								</Notes>
								<ChildNodes>
									<StdCodes IDREF="CD.0025" IncludeStd="Std"/>
								</ChildNodes>
							</Element>
						</ChildNodes>
					</Composite>
					<Element>
						<ID>0026</ID>
						<Name>Application reference</Name>
						<StdRequirement>C</StdRequirement>
						<UsrRequirement>U</UsrRequirement>
						<Sequence>070</Sequence>
						<DataType>an</DataType>
						<MinSize>1</MinSize>
						<MaxSize>14</MaxSize>
						<MaxUse>1</MaxUse>
						<Notes>
							<Note Type="Description">Identification of the application area assigned by the  sender, to which the messages in the interchange relate  e.g. the message identifier if all the messages in the  interchange are of the same type.</Note>
						</Notes>
					</Element>
					<Element>
						<ID>0029</ID>
						<Name>Processing priority code</Name>
						<StdRequirement>C</StdRequirement>
						<UsrRequirement>U</UsrRequirement>
						<Sequence>080</Sequence>
						<DataType>a</DataType>
						<MinSize>1</MinSize>
						<MaxSize>1</MaxSize>
						<MaxUse>1</MaxUse>
						<Notes>
							<Note Type="Description">Code determined by the sender requesting processing  priority for the interchange.</Note>
						</Notes>
						<ChildNodes>
							<StdCodes IDREF="CD.0029" IncludeStd="Std"/>
						</ChildNodes>
					</Element>
					<Element>
						<ID>0031</ID>
						<Name>Acknowledgement request</Name>
						<StdRequirement>C</StdRequirement>
						<UsrRequirement>U</UsrRequirement>
						<Sequence>090</Sequence>
						<DataType>n</DataType>
						<MinSize>1</MinSize>
						<MaxSize>1</MaxSize>
						<MaxUse>1</MaxUse>
						<Notes>
							<Note Type="Description">Code determined by the sender for acknowledgement of the  interchange.</Note>
						</Notes>
						<ChildNodes>
							<StdCodes IDREF="CD.0031" IncludeStd="Std"/>
						</ChildNodes>
					</Element>
					<Element>
						<ID>0032</ID>
						<Name>Cummunications agreement ID</Name>
						<StdRequirement>C</StdRequirement>
						<UsrRequirement>U</UsrRequirement>
						<Sequence>100</Sequence>
						<DataType>an</DataType>
						<MinSize>1</MinSize>
						<MaxSize>35</MaxSize>
						<MaxUse>1</MaxUse>
						<Notes>
							<Note Type="Description">Identification by name or code of the type of agreement  under which the interchange takes place.</Note>
						</Notes>
					</Element>
					<Element>
						<ID>0035</ID>
						<Name>Test indicator</Name>
						<StdRequirement>C</StdRequirement>
						<UsrRequirement>U</UsrRequirement>
						<Sequence>110</Sequence>
						<DataType>n</DataType>
						<MinSize>1</MinSize>
						<MaxSize>1</MaxSize>
						<MaxUse>1</MaxUse>
						<Notes>
							<Note Type="Description">Indication that the interchange is a test.</Note>
						</Notes>
						<ChildNodes>
							<StdCodes IDREF="CD.0035" IncludeStd="Std"/>
						</ChildNodes>
					</Element>
				</ChildNodes>
			</Segment>
			<Segment>
				<ID>UNG</ID>
				<Name>FUNCTIONAL GROUP HEADER</Name>
				<StdRequirement>C</StdRequirement>
				<UsrRequirement>U</UsrRequirement>
				<Area>0</Area>
				<Sequence/>
				<MaxUse>1</MaxUse>
				<Notes>
					<Note Type="Purpose">To head, identify and specify a functional group.</Note>
				</Notes>
				<ChildNodes>
					<Element>
						<ID>0038</ID>
						<Name>Functional group identification</Name>
						<StdRequirement>M</StdRequirement>
						<UsrRequirement>MU</UsrRequirement>
						<Sequence>010</Sequence>
						<DataType>an</DataType>
						<MinSize>1</MinSize>
						<MaxSize>6</MaxSize>
						<MaxUse>1</MaxUse>
						<Notes>
							<Note Type="Description">Identification of the one type of messages in a functional  group.</Note>
						</Notes>
					</Element>
					<Composite>
						<ID>S006</ID>
						<Name>APPLICATION SENDER'S IDENTIFICATION</Name>
						<StdRequirement>M</StdRequirement>
						<UsrRequirement>MU</UsrRequirement>
						<Sequence>020</Sequence>
						<MaxUse>1</MaxUse>
						<Notes>
							<Note Type="Description">Identification of the sender's division, department etc.  from which a group of messages is sent.</Note>
						</Notes>
						<ChildNodes>
							<Element>
								<ID>0040</ID>
								<Name>Application sender's identification</Name>
								<StdRequirement>M</StdRequirement>
								<UsrRequirement>U</UsrRequirement>
								<Sequence>010</Sequence>
								<DataType>an</DataType>
								<MinSize>1</MinSize>
								<MaxSize>35</MaxSize>
								<MaxUse>1</MaxUse>
								<Notes>
									<Note Type="Description">Name or code identifying the originating division,  department etc. within the sender's organization.</Note>
								</Notes>
							</Element>
							<Element>
								<ID>0007</ID>
								<Name>Partner identification code qualifier</Name>
								<StdRequirement>C</StdRequirement>
								<UsrRequirement>U</UsrRequirement>
								<Sequence>020</Sequence>
								<DataType>an</DataType>
								<MinSize>1</MinSize>
								<MaxSize>4</MaxSize>
								<MaxUse>1</MaxUse>
								<Notes>
									<Note Type="Description">Qualifier referring to the source of codes for the  identifiers of interchanging partners.</Note>
								</Notes>
								<ChildNodes>
									<StdCodes IDREF="CD.0007" IncludeStd="Std"/>
								</ChildNodes>
							</Element>
						</ChildNodes>
					</Composite>
					<Composite>
						<ID>S007</ID>
						<Name>APPLICATION RECIPIENTS IDENTIFICATION</Name>
						<StdRequirement>M</StdRequirement>
						<UsrRequirement>MU</UsrRequirement>
						<Sequence>030</Sequence>
						<MaxUse>1</MaxUse>
						<Notes>
							<Note Type="Description">Identification of the recipient's division, department etc.  for which a group of messages is intended.</Note>
						</Notes>
						<ChildNodes>
							<Element>
								<ID>0044</ID>
								<Name>Application recipient's identification</Name>
								<StdRequirement>M</StdRequirement>
								<UsrRequirement>U</UsrRequirement>
								<Sequence>010</Sequence>
								<DataType>an</DataType>
								<MinSize>1</MinSize>
								<MaxSize>35</MaxSize>
								<MaxUse>1</MaxUse>
								<Notes>
									<Note Type="Description">Name or code identifying the division, department etc.  within the recipient's organization for which the group of  messages is intended.</Note>
								</Notes>
							</Element>
							<Element>
								<ID>0007</ID>
								<Name>Partner identification code qualifier</Name>
								<StdRequirement>C</StdRequirement>
								<UsrRequirement>U</UsrRequirement>
								<Sequence>020</Sequence>
								<DataType>an</DataType>
								<MinSize>1</MinSize>
								<MaxSize>4</MaxSize>
								<MaxUse>1</MaxUse>
								<Notes>
									<Note Type="Description">Qualifier referring to the source of codes for the  identifiers of interchanging partners.</Note>
								</Notes>
								<ChildNodes>
									<StdCodes IDREF="CD.0007" IncludeStd="Std"/>
								</ChildNodes>
							</Element>
						</ChildNodes>
					</Composite>
					<Composite>
						<ID>S004</ID>
						<Name>DATE/TIME OF PREPARATION</Name>
						<StdRequirement>M</StdRequirement>
						<UsrRequirement>MU</UsrRequirement>
						<Sequence>040</Sequence>
						<MaxUse>1</MaxUse>
						<Notes>
							<Note Type="Description">Date/time of preparation of the interchange.</Note>
						</Notes>
						<ChildNodes>
							<Element>
								<ID>0017</ID>
								<Name>Date of preparation</Name>
								<StdRequirement>M</StdRequirement>
								<UsrRequirement>U</UsrRequirement>
								<Sequence>010</Sequence>
								<DataType>n</DataType>
								<MinSize>6</MinSize>
								<MaxSize>6</MaxSize>
								<MaxUse>1</MaxUse>
								<Notes>
									<Note Type="Description">Local date when an interchange or a functional group was  prepared.</Note>
								</Notes>
							</Element>
							<Element>
								<ID>0019</ID>
								<Name>Time of preparation</Name>
								<StdRequirement>M</StdRequirement>
								<UsrRequirement>U</UsrRequirement>
								<Sequence>020</Sequence>
								<DataType>n</DataType>
								<MinSize>4</MinSize>
								<MaxSize>4</MaxSize>
								<MaxUse>1</MaxUse>
								<Notes>
									<Note Type="Description">Local time of day when an interchange or a functional group  was prepared.</Note>
								</Notes>
							</Element>
						</ChildNodes>
					</Composite>
					<Element>
						<ID>0048</ID>
						<Name>Functional group reference number</Name>
						<StdRequirement>M</StdRequirement>
						<UsrRequirement>MU</UsrRequirement>
						<Sequence>050</Sequence>
						<DataType>an</DataType>
						<MinSize>1</MinSize>
						<MaxSize>14</MaxSize>
						<MaxUse>1</MaxUse>
						<Notes>
							<Note Type="Description">Reference number for the functional group assigned by and  unique within the sender's division, department etc.</Note>
						</Notes>
					</Element>
					<Element>
						<ID>0051</ID>
						<Name>Controlling agency</Name>
						<StdRequirement>M</StdRequirement>
						<UsrRequirement>MU</UsrRequirement>
						<Sequence>060</Sequence>
						<DataType>an</DataType>
						<MinSize>1</MinSize>
						<MaxSize>2</MaxSize>
						<MaxUse>1</MaxUse>
						<ChildNodes>
							<StdCodes IDREF="CD.0051" IncludeStd="Std"/>
						</ChildNodes>
					</Element>
					<Composite>
						<ID>S008</ID>
						<Name>MESSAGE VERSION</Name>
						<StdRequirement>M</StdRequirement>
						<UsrRequirement>MU</UsrRequirement>
						<Sequence>070</Sequence>
						<MaxUse>1</MaxUse>
						<Notes>
							<Note Type="Description">Specification of the type of messages in the functional  group.</Note>
						</Notes>
						<ChildNodes>
							<Element>
								<ID>0052</ID>
								<Name>Message type versiion number</Name>
								<StdRequirement>M</StdRequirement>
								<UsrRequirement>U</UsrRequirement>
								<Sequence>010</Sequence>
								<DataType>an</DataType>
								<MinSize>1</MinSize>
								<MaxSize>3</MaxSize>
								<MaxUse>1</MaxUse>
							</Element>
							<Element>
								<ID>0054</ID>
								<Name>Message type release number</Name>
								<StdRequirement>M</StdRequirement>
								<UsrRequirement>U</UsrRequirement>
								<Sequence>020</Sequence>
								<DataType>an</DataType>
								<MinSize>1</MinSize>
								<MaxSize>3</MaxSize>
								<MaxUse>1</MaxUse>
							</Element>
						</ChildNodes>
					</Composite>
					<Element>
						<ID>0058</ID>
						<Name>Application password</Name>
						<StdRequirement>C</StdRequirement>
						<UsrRequirement>U</UsrRequirement>
						<Sequence>080</Sequence>
						<DataType>an</DataType>
						<MinSize>1</MinSize>
						<MaxSize>14</MaxSize>
						<MaxUse>1</MaxUse>
						<Notes>
							<Note Type="Description">Password to the recipient's division, department or  sectional system.</Note>
						</Notes>
					</Element>
				</ChildNodes>
			</Segment>
			<Loop><!-- HEADER SECTION START-->
				<ID>Envelope</ID>
				<Name/>
				<StdRequirement>M</StdRequirement>
				<UsrRequirement>M</UsrRequirement>
				<Area>0</Area>
				<Sequence>AAAA</Sequence>
				<Count>999</Count>
				<Notes>
					<Note Type="User Notes">Envelope loop added by SE</Note>
				</Notes>
				
				
				<ChildNodes>
					<Segment>
						<ID>UNH</ID>
						<Name>MESSAGE HEADER</Name>
						<StdRequirement>M</StdRequirement>
						<UsrRequirement>MU</UsrRequirement>
						<Area>0</Area>
						<Sequence>0010</Sequence>
						<MaxUse>1</MaxUse>
						<Notes>
							<Note Type="SetNotes">A service segment starting and uniquely identifying a  message. The message type code for the UN International  Multimodal Status Report Message is IFTSTA. Note:  International Multimodal Status Report messages conforming  to this document must contain the following data in segment  UNH, ComPosite S009:Data element 0065 IFTSTA  0052 D  0054  93A  0051 UN</Note>
						</Notes>
						<ChildNodes>
							<Element>
								<ID>0062</ID>
								<Name>Message reference number</Name>
								<StdRequirement>M</StdRequirement>
								<UsrRequirement>MU</UsrRequirement>
								<Sequence>010</Sequence>
								<DataType>an</DataType>
								<MinSize>1</MinSize>
								<MaxSize>14</MaxSize>
								<MaxUse>1</MaxUse>
							</Element>
							<Composite>
								<ID>S009</ID>
								<Name>MESSAGE IDENTIFIER</Name>
								<StdRequirement>M</StdRequirement>
								<UsrRequirement>MU</UsrRequirement>
								<Sequence>020</Sequence>
								<MaxUse>1</MaxUse>
								<ChildNodes>
									<Element>
										<ID>0065</ID>
										<Name>Message type identifier</Name>
										<StdRequirement>M</StdRequirement>
										<UsrRequirement>MU</UsrRequirement>
										<Sequence>010</Sequence>
										<DataType>an</DataType>
										<MinSize>1</MinSize>
										<MaxSize>6</MaxSize>
										<MaxUse>1</MaxUse>
										<ChildNodes>
											<StdCodes IDREF="CD.0065" IncludeStd="Std"/>
										</ChildNodes>
									</Element>
									<Element>
										<ID>0052</ID>
										<Name>Message type versiion number</Name>
										<StdRequirement>M</StdRequirement>
										<UsrRequirement>MU</UsrRequirement>
										<Sequence>020</Sequence>
										<DataType>an</DataType>
										<MinSize>1</MinSize>
										<MaxSize>3</MaxSize>
										<MaxUse>1</MaxUse>
									</Element>
									<Element>
										<ID>0054</ID>
										<Name>Message type release number</Name>
										<StdRequirement>M</StdRequirement>
										<UsrRequirement>MU</UsrRequirement>
										<Sequence>030</Sequence>
										<DataType>an</DataType>
										<MinSize>1</MinSize>
										<MaxSize>3</MaxSize>
										<MaxUse>1</MaxUse>
									</Element>
									<Element>
										<ID>0051</ID>
										<Name>Controlling agency</Name>
										<StdRequirement>M</StdRequirement>
										<UsrRequirement>MU</UsrRequirement>
										<Sequence>040</Sequence>
										<DataType>an</DataType>
										<MinSize>1</MinSize>
										<MaxSize>2</MaxSize>
										<MaxUse>1</MaxUse>
										<ChildNodes>